version: '3.9'
services:
  app:
    image: amazon/aws-glue-libs:glue_libs_4.0.0_image_01
    user: root
    container_name: test_dev
    volumes:
      - ..:/workspace
      - ./spark-conf:/home/glue_user/spark/conf
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
  storage:
    image: minio/minio
    volumes:
      - ../minio_storage:/data
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      - minio_env
    command: server --console-address ":9001" /data