version: '3.9'
services:
  app:
    image: amazon/aws-glue-libs:glue_libs_4.0.0_image_01
    container_name: test_dev
    volumes:
      - ..:/workspace
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
